// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvwletzdmbvobgaqnavf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2d2xldHpkbWJ2b2JnYXFuYXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MTMxODIsImV4cCI6MjA3MDE4OTE4Mn0.alh9jxx8_Xwl1RwRnTuzRpiNxNVyF565A2kTuzDTaQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});